# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: the-tcpdump-group/tcpdump

    - name: setup sdk file
      shell: bash
      run: |
        curl -O https://npcap.com/dist/npcap-sdk-1.13.zip;
        unzip -d npcap-sdk-1.13        npcap-sdk-1.13.zip;
        ls -l;
        
    
    # https://github.com/the-tcpdump-group/tcpdump/blob/master/doc/README.windows.md#visual-studio-2022
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake "-DPCAP_ROOT=npcap-sdk-1.13" -G "Visual Studio 17 2022" -A x64 .
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      
    - name: Build
      # Build your program with the given configuration
      run: msbuild /m /nologo /p:Configuration=Release tcpdump.sln

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact-tcpdump
        path: ./Release
        compression-level: 9 # maximum compression
        retention-days: 7



